### ISSUE TITLE
selected source image build does not support custom component removal

### ISSUE THREAD

**Issue by geextahslex** [thecodermehedi/msmg-toolkit#12]
MSMG toolkit: v13.5
ISO: latest Windows 10 22H2 from Microsoft

Hi,
What can I do about this, I have this .iso from microsoft and get this message
I want to use the normal removal option and not DISM
![msmg bug 2](https://github.com/devbytemehedi/msmg-toolkit/assets/139760266/97153e68-2f79-483d-9277-f02a6b47e7fd)

**Comment by IntNinja** [comment]
following up 22h2, component removal isn't supported

**Comment by elvisisvan** [comment]
> following up 22h2, component removal isn't supported

looks like microsoft has further tighten customizability to its windows product, guess we have to choose older builds for this to work
